DB=[Id, createdAt, one, two, three, four five, six, seven, eight...
    feedback_max, feedback_prev, hamming_best, hamming_prev, level...
    lookedAtHelp, reference_prev, max_so_far_index, score, session...
    submissionOrder, char(usedHelp), interdep, MB, succ_f, x, y]; 

data_cells=num2cell(DB);
  col_header={'Id', 'createdAt',  'one', 'two', 'three', 'four', 'five', 'six' ...
      'seven', 'eight', 'feedback_max', 'feedback_prev', 'hamming_best'...
      'hamming_prev'...
      'level', 'lookedAtHelp', 'reference_prev', 'max_so_far', 'score', 'session'...
      'submissionOrder', 'usedHelp', 'interdep', 'MB', 'succ_f',  'current', 'max'};
     
 filename = 'Cogs.xls';
 Game_data=[col_header; data_cells];
xlswrite(filename,Game_data,'Sheet1');